### PR TITLE
Hardening removing pre-post snapshots.

### PR DESCRIPTION
**Pull request by varkoly**
The reason of this PR is: https://bugzilla.suse.com/show_bug.cgi?id=1181050#c22
I think this calls are more effektiv. I've tested it and it works with a lot of snapshots without error.

### CODE REVIEW

**Comment by angelabriel** [comment]
You are more or less back to the code before Egbert changed it in https://github.com/SUSE/clone-master-clean-up/commit/584417a08d3782e49685e1130d3f88eae2f8d3c4 because of some output format changes between SLE12 and SLE15 (see https://github.com/SUSE/clone-master-clean-up/pull/5 too)
And see https://bugzilla.suse.com/show_bug.cgi?id=1149322
May be discuss the details with Egbert as he was working on the bug.

**Review by e4t — CHANGES_REQUESTED** [review]
Have you checked whether the --columns arg is available in earlier products that are still supported (under LTSS)? The sole reason for the huge convoluted script was that snapper had changed its output format in an incompatible way.
At the time I called out the people responsible for this (see bsc#1149322) so this option was implemented as a result of this (see comment #26). If this has been backported to all supported code streams, fine. If not, you may at least have to follow the suggestion in comment #36 and distinguish by version number.
Beware that you will have to support at least 3 different versions:
1. the 'old' output format.
2. the 'new' one with fields switched around.
3. the one supporting the --columns option.
You ought to make sure code works on all supported code streams, as this will make things like security fixes much easier.

**Comment by angelabriel** [comment]
The latest fix with '--columns' does NOT work on SLE12SP5

rpm -q snapper
snapper-0.5.0.1-3.3.1.x86_64

zypper up snapper
Refreshing service 'SUSE_Linux_Enterprise_Server_for_SAP_Applications_12_SP5_x86_64'.
Loading repository data...
Reading installed packages...
No update candidate for 'snapper-0.5.0.1-3.3.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...

 snapper list --columns number,type
Unknown option '--columns' for command 'list'.
Try 'snapper --help' for more information.

As SLE12SP5 is still supported, you may need to go with the 'old' coding for SLE12SP5. SLE15, SLE15SP1 and only starting with SLE15SP2 you can use the 'new' style. In this case the spec file should include a 'require snapper >= 0.8.6' for 'sle_version >= 150200' to be sure the needed functionality will be available.

**Comment by varkoly** [comment]
I've made searching of snapshots independent from snapper version.
I've splited removing snapshots in two steps and use --sync to avoid errors.
First pre then the post snapshots

**Review by angelabriel — APPROVED** [review]
Did not test the changes as my test system with btrfs is currently broken, but looks good to me. Thanks for taking our concerns seriously.

**Pull request merged**
